### ISSUE TITLE
Fix location when submitting order

### ISSUE THREAD

**Issue by wjinyan** [ono-otw/ono-otw#96]
Please do work for this task in a branch named issue-96.

![image](https://user-images.githubusercontent.com/56209781/81779030-9472b100-948f-11ea-83e6-f49c1317966e.png)

At the moment, if you leave the location it still allows you to submit. But because the location is empty, it doesn't correctly get added due to the pendingOrderSchema requiring location.

**Comment by jhsuP** [comment]
![image](https://user-images.githubusercontent.com/56209781/81880014-026ab700-9528-11ea-87ba-88ddf9a50aa7.png)
